import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Counter from '../components/Counter'
import UserProfile from '../components/UserProfile'
import wrapper from '../store'
import { loadUser } from '../actions/count'

export const getStaticProps = wrapper.getStaticProps( (store) => async ({preview}) => {
   await store.dispatch(loadUser());
})

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         <div className={styles.box}>
            <UserProfile />
         </div>
      </main>
    </div>
  )
}

export default Home