import { useCallback, useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSelector } from 'react-redux'
import { RootState } from '../store'
import { loadUser } from '../actions/count'
import { useAppDispatch } from '../store'
import {increment, decrement} from '../slices/count';

const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const {val, user} = useSelector((state:RootState) => {
    return state.count
  });

  useEffect(()=> {
    dispatch(loadUser());
  }, []);

  const onIncrement = useCallback(()=>dispatch(increment()), [])

  const onDecrement = useCallback(()=>dispatch(decrement()), []) 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
         <div className={styles.box}>
              <span>{val}</span>
              <div className={styles.btnBox}>
                  <button onClick={onIncrement}>+</button>
                  <button onClick={onDecrement}>-</button>
              </div>
              <div className='load-user'>
                  {user?.first_name}
              </div>
         </div>
      </main>
    </div>
  )
}

export default Home